config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    namespace :api do
        namespace :v1 do
            get  '/resources', to: 'api#index',  as: 'index'
            post '/resources', to: 'api#create', as: 'create'
        end
    end


    root 'gui#index'

    get  '/resource/new(.:format)',      to: 'gui#new',                  as: 'new_resource'
    post '/resource(.:format)',          to: 'resource#create',          as: 'create_resource'
    get  '/resource/override(.:format)', to: 'gui#override',             as: 'new_override'
    post '/resource/override(.:format)', to: 'resource#create_override', as: 'create_override'
end

app/controllers/gui_controller.rb
require "#{Rails.root}/app/workers/capability_worker.rb"
require "#{Rails.root}/lib/capability.rb"

class GuiController < ApplicationController
    def index
        # an idea is to show a list of current capabilities (atm; resources later)
        @resources = Resource.all
    end

    def new
        @capabilities = {
            sound: ['Sound','bullhorn'],
            illumination: ['Illumination','lamp'],
            car_flow: ['Car Flow','road'],
            people_density: ['People Density','user'],
            video: ['Video','facetime-video'],
            weather: ['Weather','cloud'],
            air_quality: ['Air Quality','leaf']
        }
    end

    def override
        sess_to_res
    end

    private
        def sess_to_res
            sr = session[:resource]
            @r = Resource.new
            @r.capabilities = sr['capabilities']
            @r.latitude,@r.longitude = sr['latitude'], sr['longitude']
            @r.description = sr['description']
        end
end

app/helpers/gui_helper.rb
module GuiHelper
end

app/views/gui/index.html.erb
<div class="container-fluid text-center">
    <h1>Resources</h1>

    <%= render partial: "layouts/flash_message" %>

    <% if @resources.size > 0 %>
        <div class="row">
            <div class="col-md-1"></div>

            <div class="col-md-3 theader">UUID</div>
            <div class="col-md-2 theader">Coordinates</div>
            <div class="col-md-5 theader">Capabilities</div>

            <div class="col-md-1"></div>
        </div>

        <% @resources.each do |res| %>
            <div class="row">
                <div class="col-md-1"></div>

                <div class="col-md-3 tbody"><%= res.uuid %></div>
                <div class="col-md-2 tbody"><%= "(#{res.latitude}, #{res.longitude})" %></div>
                <div class="col-md-5 tbody"><%= res.capabilities.map{|s|s.gsub('_',' ')}.join ', ' %></div>

                <div class="col-md-1"></div>
            </div>
        <% end %>
    <% else %>
    <br><br><br><br>
    <% end %>

    <div class="form-group">
        <%= link_to 'New resource', new_resource_path, class: 'btn btn-default' %>
    </div>
</div>

app/views/gui/new.html.erb
<div class="container-fluid text-center">
    <h1>Create a new Resource</h1>

    <%= render partial: "layouts/flash_message" %>

    <%= form_tag(create_resource_path, method: 'post', class: 'form-inline', id: 'form') do %>
        <div id="checkbox-group">
            <% @capabilities.each do |k,v|%>
                <div class="form-group well">
                    <%
                        checked = false
                        checked = true if !params[:options].nil? and params[:options].include? k.to_s
                    %>
                    <%= check_box_tag "options[]", k.to_s, checked %>
                    <span class="glyphicon glyphicon-<%=v[1]%>"></span>
                    <%= label_tag(k,v[0].to_s) %>
                </div>
            <% end %>
        </div>

        <br><br>

        <div class="form-group">
          <%= label_tag(:description,'Description :') %><br>
            <%= text_field_tag(:description, params[:description], {maxlength: 255, minlength: 5, placeholder: 'a small briefing', size: 50}) %>
        </div>

        <br><br>

        <div class="form-group">
          <%= label_tag :coordinates, "Coordinates: " %><br>
          <%= text_field_tag :coordinates, params[:coordinates], {placeholder: 'click the map below', size: 50} %>
          <!-- <input type="text" name='coordinates' id='coordinates' placeholder="click in the map below" size=50> -->

            <br><br>

            <main role="main" class="container">
                <div height="150" style="border:0; width: 100%" id="map2"></div>
            </main>
        </div>

        <br><br>

        <div class='form-group'>
            <%= check_box_tag "override", true %>
            <%= label_tag :override,"Override a capability behavior" %>
            <p class='small'>Selecting this will lead you to another form</p>
        </div>

        <br><br>

        <div class='form-group' id='submit_btn'>
            <%= submit_tag("Create Resource", class: 'btn btn-default btn-lg') %>
        </div>
    <% end %>

    <br>

    <%= link_to 'Back', root_path, class: 'btn btn-link' %>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
<!-- <script src="app/assets/javascripts/min.js" > -->

<script type="text/javascript">
  new SampaMap('map1');
  new SampaMap('map2', function(lat, lon) {
    $('#coordinates').val(lat + "; " + lon);
  });
</script>

app/views/gui/override.html.erb
<div class="container-fluid text-center">
    <h1>Override behaviors</h1>

    <div class='alert alert-info'>
        <p>Note that you must fill <strong>at least</strong> one field</p>
        <p>Example:<br>
            Suppose you want the data to be generated according to the sine distribution, then you're <strong>Ruby code</strong> should be something like this:<br>
            <code>Math.sin(Time.now.hour * Math::PI)</code><br>
            For instance, suppose now it's 10:23 a.m., the data generated <em>now</em> will be sin(10 * pi) = 0.
        </p>
    </div>

    <%= render partial: "layouts/flash_message" %>

    <div>
    </div>

    <%= form_tag(create_override_path, method: 'post', class: 'form-inline', id: 'form') do %>

        <% @r.capabilities.each do |k,v| %>
            <div class='form-group well'>
                
                <h3> <%= label_tag k,v %> </h3>

                <div class='form-group'>
                    <%= label_tag "Refresh Rate: " %>
                    <%= number_field_tag "#{k}_send_amount", params["{k}_send_amount"], min:1 %>
                    <%= select_tag "#{k}_send_unity", options_for_select([ "Hours", "Minutes" ], "Minutes") %>
                </div>
                <br>
                
                <%= text_area_tag "#{k}_code",nil,rows: 10, cols: 60 %>
                <br>
            </div>
            <br>
        <% end %>
        <br>

        <div class='form-group' id='submit_btn'>
            <%= submit_tag("Create Resource", class: 'btn btn-default btn-lg') %>
        </div>

    <% end %>

    <br>

    <%= link_to 'Back', root_path, class: 'btn btn-link' %>
</div>